### PR TITLE
Linting & Typo fixes from Stéphane Aulery

### PR DESCRIPTION
**Pull request by mischat**
Hey @lkppo what do you think, are these the fixes you asked for ?

### CODE REVIEW

**Comment by lkppo** [comment]
Yes, exactly.

**Comment by mischat** [comment]
@swh let me know if you are happy with this and i can merge the pull request in ...

**Comment by lkppo** [comment]
Yes I am, and Lintian too. Some text was hidden. There are others errors about - escaping and empty lines, but I will no mix patches. I can make a second pull request after your commit.

**Comment by swh** [comment]
Sure, go for it.

**Comment by swh** [comment]
Looks like straight-up typos

**Comment by lkppo** [comment]
Thanks a lot !

**Pull request merged**
